//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.WEB08.PNNHAI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.WEB08.PNNHAI.Core.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token không hợp lệ..
        /// </summary>
        public static string AccessTokenInvalidError {
            get {
                return ResourceManager.GetString("AccessTokenInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token chưa hết hạn không thể làm mới..
        /// </summary>
        public static string AccessTokenNotExpiredCantRefreshError {
            get {
                return ResourceManager.GetString("AccessTokenNotExpiredCantRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token không được gửi lên..
        /// </summary>
        public static string AccessTokenNotPostedError {
            get {
                return ResourceManager.GetString("AccessTokenNotPostedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại mã định danh không thỏa mãn..
        /// </summary>
        public static string ContainsInvalidIdError {
            get {
                return ResourceManager.GetString("ContainsInvalidIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu không đúng mẫu! Tồn tại cột không thỏa mãn dữ liệu quản lý..
        /// </summary>
        public static string ContainWrongColumnInFilePosted {
            get {
                return ResourceManager.GetString("ContainWrongColumnInFilePosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại gửi lên không khớp..
        /// </summary>
        public static string CurrentPasswordPostedNotMatchedError {
            get {
                return ResourceManager.GetString("CurrentPasswordPostedNotMatchedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} xung đột kiểu dữ liệu..
        /// </summary>
        public static string DataConflict {
            get {
                return ResourceManager.GetString("DataConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string DateOfBirthNoMoreThanCurrent {
            get {
                return ResourceManager.GetString("DateOfBirthNoMoreThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách id gửi lên rỗng..
        /// </summary>
        public static string DeleteIdsEmptyError {
            get {
                return ResourceManager.GetString("DeleteIdsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công..
        /// </summary>
        public static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại..
        /// </summary>
        public static string DepartmentNotExistedError {
            get {
                return ResourceManager.GetString("DepartmentNotExistedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại trong hệ thống..
        /// </summary>
        public static string EmailExistedError {
            get {
                return ResourceManager.GetString("EmailExistedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng..
        /// </summary>
        public static string EmailWrongFormat {
            get {
                return ResourceManager.GetString("EmailWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên {0} tồn tại trong hệ thống..
        /// </summary>
        public static string EmployeeCodeContainsInDB {
            get {
                return ResourceManager.GetString("EmployeeCodeContainsInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên {0} tồn tại trong tệp nhập khẩu..
        /// </summary>
        public static string EmployeeCodeContainsInImportFile {
            get {
                return ResourceManager.GetString("EmployeeCodeContainsInImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên sai định dạng. (Dạng NV-...).
        /// </summary>
        public static string EmployeeCodeWrongFormat {
            get {
                return ResourceManager.GetString("EmployeeCodeWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng thực thi chưa phù hợp..
        /// </summary>
        public static string ExecuteObjectNotSuitable {
            get {
                return ResourceManager.GetString("ExecuteObjectNotSuitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên {0} đã tồn tại..
        /// </summary>
        public static string ExistedEmployeeCode {
            get {
                return ResourceManager.GetString("ExistedEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép để trống..
        /// </summary>
        public static string FieldRequiredError {
            get {
                return ResourceManager.GetString("FieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại ! Vui lòng thử lại..
        /// </summary>
        public static string FileNotFoundError {
            get {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập.
        /// </summary>
        public static string ForbiddenError {
            get {
                return ResourceManager.GetString("ForbiddenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Gender_Orther {
            get {
                return ResourceManager.GetString("Gender_Orther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp CCCD không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string IdentityIssuedDateNoMoreThanCurrent {
            get {
                return ResourceManager.GetString("IdentityIssuedDateNoMoreThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu nhập khẩu không có hoặc đã quá thời gian xử lý..
        /// </summary>
        public static string ImportDataNotFountOrTimeout {
            get {
                return ResourceManager.GetString("ImportDataNotFountOrTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị nhập vào không được lơn hơn ngày hiện tại..
        /// </summary>
        public static string InputDateNoMoreThanCurrentDateDefault {
            get {
                return ResourceManager.GetString("InputDateNoMoreThanCurrentDateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công..
        /// </summary>
        public static string InsertSuccessful {
            get {
                return ResourceManager.GetString("InsertSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có giá trị không hợp lệ..
        /// </summary>
        public static string InvalidValueError {
            get {
                return ResourceManager.GetString("InvalidValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định sai định dạng..
        /// </summary>
        public static string LandlineNumberWrongFormat {
            get {
                return ResourceManager.GetString("LandlineNumberWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập không hợp lệ..
        /// </summary>
        public static string LoginInforInvalidError {
            get {
                return ResourceManager.GetString("LoginInforInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được phép thực hiện xóa tối đa {0} bản ghi..
        /// </summary>
        public static string MoreRecordDeleteError {
            get {
                return ResourceManager.GetString("MoreRecordDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu muốn thay đổi không khác mật khẩu hiện tại..
        /// </summary>
        public static string NewPasswordMatchedCurrentPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordMatchedCurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin theo Id..
        /// </summary>
        public static string NotFoundById {
            get {
                return ResourceManager.GetString("NotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có chức năng nhập khẩu với đối tượng này..
        /// </summary>
        public static string NotImplementWithObjError {
            get {
                return ResourceManager.GetString("NotImplementWithObjError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại trong hệ thống..
        /// </summary>
        public static string PhoneNumberExistedError {
            get {
                return ResourceManager.GetString("PhoneNumberExistedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động sai định dạng..
        /// </summary>
        public static string PhoneNumberWrongFormat {
            get {
                return ResourceManager.GetString("PhoneNumberWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu gửi lên không có dữ liệu..
        /// </summary>
        public static string PostedFileWithNoData {
            get {
                return ResourceManager.GetString("PostedFileWithNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã gửi tệp với sheet không thỏa mãn lên..
        /// </summary>
        public static string PostedWithWrongSheet {
            get {
                return ResourceManager.GetString("PostedWithWrongSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token đã hết hạn..
        /// </summary>
        public static string RefreshTokenExpiredError {
            get {
                return ResourceManager.GetString("RefreshTokenExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token không tồn tại..
        /// </summary>
        public static string RefreshTokenNotExistedError {
            get {
                return ResourceManager.GetString("RefreshTokenNotExistedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token không được gửi lên..
        /// </summary>
        public static string RefreshTokenNotPostedError {
            get {
                return ResourceManager.GetString("RefreshTokenNotPostedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ chấp nhận tệp excel (.xlsx)..
        /// </summary>
        public static string SendWithoutExcelFileError {
            get {
                return ResourceManager.GetString("SendWithoutExcelFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có file nào được gửi lên..
        /// </summary>
        public static string SendWithoutFileError {
            get {
                return ResourceManager.GetString("SendWithoutFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ Misa để được giúp đỡ..
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token gửi lên không hợp lệ..
        /// </summary>
        public static string TokenPostedInvalidError {
            get {
                return ResourceManager.GetString("TokenPostedInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token đã bị thu hồi hoặc hết hạn..
        /// </summary>
        public static string TokenRevokedOrExpiredError {
            get {
                return ResourceManager.GetString("TokenRevokedOrExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực người dùng không thành công.
        /// </summary>
        public static string UnauthorizeError {
            get {
                return ResourceManager.GetString("UnauthorizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại..
        /// </summary>
        public static string UserNotExistedError {
            get {
                return ResourceManager.GetString("UserNotExistedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có giá trị không tồn tại..
        /// </summary>
        public static string ValueNotFound {
            get {
                return ResourceManager.GetString("ValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu không đúng mẫu! Số lượng cột trong tệp khác số lượng quản lý..
        /// </summary>
        public static string WrongColumnCountWithTemplateInFile {
            get {
                return ResourceManager.GetString("WrongColumnCountWithTemplateInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cột thực hiện lọc không tồn tại..
        /// </summary>
        public static string WrongFilterColumn {
            get {
                return ResourceManager.GetString("WrongFilterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu không đúng mẫu! Thứ tự các cột không chính xác..
        /// </summary>
        public static string WrongOrderOfColumnInFilePosted {
            get {
                return ResourceManager.GetString("WrongOrderOfColumnInFilePosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn không phù hợp. Vui lòng thử lại..
        /// </summary>
        public static string WrongSelectionError {
            get {
                return ResourceManager.GetString("WrongSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sai giá trị..
        /// </summary>
        public static string WrongValueError {
            get {
                return ResourceManager.GetString("WrongValueError", resourceCulture);
            }
        }
    }
}
